# faça um programa que leia um numero inteiro qualquer e mostre a sua tabuada
from time import sleep
print('Tabuada')
n=int(input('Digite o numero para a tabuada:'))
if n >= 11:
    print('Ta me achado com carra de calculadora?')
    print('Calculando...')
    sleep(2)
    print('\033[30m='*12)
    print('{} x {:2} = {}'.format(n, 1, n*1))
    print('{} x {:2} = {}'.format(n, 2, n*2))
    print('{} x {:2} = {}'.format(n, 3, n*3))
    print('{} x {:2} = {}'.format(n, 4, n*4))
    print('{} x {:2} = {}'.format(n, 5, n*5))
    print('{} x {:2} = {}'.format(n, 6, n*6))
    print('{} x {:2} = {}'.format(n, 7, n*7))
    print('{} x {:2} = {}'.format(n, 8, n*8))
    print('{} x {:2} = {}'.format(n, 9, n*9))
    print('{} x {:2} = {}'.format(n, 10, n*10))
    print('='*12,'\033[m')
else:
    print('\033[30m='*12)
    print('{} x {:2} = {}'.format(n, 1, n*1))
    print('{} x {:2} = {}'.format(n, 2, n*2))
    print('{} x {:2} = {}'.format(n, 3, n*3))
    print('{} x {:2} = {}'.format(n, 4, n*4))
    print('{} x {:2} = {}'.format(n, 5, n*5))
    print('{} x {:2} = {}'.format(n, 6, n*6))
    print('{} x {:2} = {}'.format(n, 7, n*7))
    print('{} x {:2} = {}'.format(n, 8, n*8))
    print('{} x {:2} = {}'.format(n, 9, n*9))
    print('{} x {:2} = {}'.format(n, 10, n*10))
    print('='*12,'\033[m')

