n = input('Digite algo:')
print('O tipo primitivo deste valor é', type(n))
print('Só tem espaço?', n.isspace())
print('É um numero?', n.isnumeric())
print('É alfabetico?', n.isalpha())
print('É alfanumerico?', n.isalnum())
print('Esta tudo em maiusculo?', n.isupper())
print('Esta tudo em minusculo?', n.islower())
print(n.isdigit())
